### ISSUE TITLE
Missing Courses in Course List

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/xikolo-android#167]
It looks like a lot of courses on mooc.house and also some on openHPI are missing in the "All Courses" view. Might be related to some date-based filtering. I tested it with the latest released version, not with latest dev version yet.

**Comment by bengelhaupt** [comment]
For `mooc.house`, the API gives me 27 courses. The app shows 14 of them. 7 of 8 currently running courses have a `end_at: null` which the app can't handle correctly. The other missing courses have `external: true` and are not displayed because of that reason.

I can build support for both cases, for the first case I would just adjust the database query and some strings. For the second, I would introduce a button leading to the external course provider via a link.

**Comment by tobiasrohloff** [comment]
Sounds good :) I'm wondering why `end_at: null` courses are not displayed. I think we already implemented something specifically for WHO already (they have custom order and labels). Anyway, please check the web for the date label of other platforms (e.g. `Since August 19, 2019`).
