### ISSUE TITLE
Scrolling in WebViews leads to ViewPager page swipes

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/xikolo-android#291]
To reproduce that behavior, open a course forum and scroll down. This leads to page swipes to the right or left (the other tabs). Probably an issue between ViewPager2 and our NestedScrollWebView.

**Comment by bengelhaupt** [comment]
So I had a look into this, fiddled around a bit and the problem is indeed the communication between `ViewPager2` and `NestedScrollWebView`. How ViewPager swiping works, is by intercepting the touch events from its inner views and checking whether the user swiped sideways. Other scrollable views call `requestDisallowInterceptTouchEvent(true)` when they do not want parent views to intercept touch events. `NestedScrollWebView` does not do this and touch events are handled by the ViewPager. The `NestedScrollWebView`'s custom scroll handling supports horizontal and vertical scrolling. So calling `requestDisallowInterceptTouchEvent(true)` on `startNestedScroll()` and `requestDisallowInterceptTouchEvent(false)` on `stopNestedScroll()` does completely disable ViewPager swiping.

The feature has been broken because `ViewPager2` also allows a vertical orientation, while `ViewPager(1)` only supports horizontal. So I guess in `ViewPager(1)` only vertical scrolling was allowed in the pager tabs and therefore the `NestedScrollWebView`.
The [documentation](https://developer.android.com/training/animation/vp2-migration#nested-scrollables) says: "ViewPager2 does not natively support nested scroll views in cases where the scroll view has the same orientation as the ViewPager2 object that contains it. [...] To support a scroll view inside a ViewPager2 object with the same orientation, you must call requestDisallowInterceptTouchEvent() on the ViewPager2 object when you expect to scroll the nested element instead."

Solutions are either disabling ViewPager swiping for the selected tab or only allowing to scroll the `NestedScrollWebView` vertically.

**Comment by bengelhaupt** [comment]
Another idea would be to check whether there is "space to scroll" so pages that are already swiped to start allow viewpager swiping. But this would need a lot of custom touch handling.
