### ISSUE TITLE
llegalStateException for AutoBundles: required fields not found in the bundle

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/xikolo-android#292]
Required fields are often empty for different AutoBundles. See the different errors [here](https://console.firebase.google.com/project/openwho-firebase/crashlytics/app/android:de.xikolo.openwho/issues/b5f0e64ce6e6ebb2fd19498172096942?time=last-thirty-days&versions=3.6%20(60)).

**Comment by bengelhaupt** [comment]
I already had a look into it but couldn't make out the problem. It only appears in v3.6, so it could be because of the new ViewPagers or a dependency update. But the parameters passed into the AutoBundle builders are always non-null asserted. Weird.

**Comment by tobiasrohloff** [comment]
We could also think about a strategy to get rid of the dependency. Is there any good alternative, maybe a (planned) AndroidX library?

**Comment by bengelhaupt** [comment]
The problem still persists. I had a look into [FragmentFactory](https://developer.android.com/reference/androidx/fragment/app/FragmentFactory), which was introduced with androidX. It allows to use Fragments without a no-argument constructor by providing the instantiation logic. There is also a tutorial on this [here](https://medium.com/capital-one-tech/android-fragmentfactory-75823af015fd). I did some experiments on the be/fragment_factory_experiments branch and found it very limited, because Fragment instantiations are identified by their class name. This results in collisions when e.g. multiple different Webview fragments with different parameters are used.
