### ISSUE TITLE
Support SD Cards for downloads and app install location

### ISSUE THREAD

**Issue by jprberlin** [openHPI/xikolo-android#3]
So they can use SD-cards.

**Comment by rhlff** [comment]
http://developer.android.com/guide/topics/data/install-location.html
http://developer.android.com/training/basics/data-storage/files.html

**Comment by rhlff** [comment]
Support for the app install on external storage is added in https://github.com/openHPI/xikolo-android/commit/8e42ae617a5b4fafad3f23a68a5a5a917d2683e0.

Android does not allows to write directly on secondary external storages in general, only for an app-private folder. This one is not accessible by other apps, thus our video and pdf files wouldn't be available for third-party apps, which is desired and currently possible. To write on public folders of the secondary external storages (like the root dir), the Android [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider.html) can be used, but this requires a UI interaction every time and the user can freely choose where to save the file. Therefore, our app would not know where the file was saved anymore. All in all, we won't support secondary external storages for file downloads because all of these reasons. Starting with Android 6, the user can format its sd card as primary external storage, in such a case every download would be stored on the sd card anyway.
